package Thomas; 

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JPanel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CM
 */
public class GuiProject extends javax.swing.JFrame {
 String name;
  int counter = 0;
    /**
     * Creates new form GuiProject
     */
    public GuiProject() {
        initComponents();
       
        this.setLocationRelativeTo(null);
       setIconImage();
    }

   

           class jPanelGradient extends JPanel {
    protected void paintComponent (Graphics g) {
    Graphics2D g2d = (Graphics2D) g;
    int width = getWidth();

    int height = getHeight();

    Color colorl = new Color (248, 244, 225);
    Color color2= new Color (116, 81, 45);
    GradientPaint gp = new GradientPaint (0,0,colorl, 180, height,color2);

    g2d.setPaint (gp);

    g2d.fillRect(0, 0, width, height);




    }}  
    


  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new jPanelGradient();
        student_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        acd_number = new javax.swing.JTextField();
        casee = new javax.swing.JTextField();
        stu_name = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sub_3 = new javax.swing.JTextField();
        sub_4 = new javax.swing.JTextField();
        sub_1 = new javax.swing.JTextField();
        sub_2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sub_6 = new javax.swing.JTextField();
        sub_5 = new javax.swing.JTextField();
        sub_7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rus_6 = new javax.swing.JTextField();
        rus_7 = new javax.swing.JTextField();
        rus_5 = new javax.swing.JTextField();
        rus_1 = new javax.swing.JTextField();
        rus_2 = new javax.swing.JTextField();
        rus_4 = new javax.swing.JTextField();
        rus_3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show = new javax.swing.JTextArea();
        GPA = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Students Data");
        setForeground(new java.awt.Color(48, 39, 0));
        setIconImages(null);

        student_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        student_name.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Acd Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Case");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        acd_number.setBackground(new java.awt.Color(236, 234, 216));
        acd_number.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        acd_number.setForeground(new java.awt.Color(107, 81, 2));

        casee.setBackground(new java.awt.Color(236, 234, 216));
        casee.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        casee.setForeground(new java.awt.Color(107, 81, 2));
        casee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseeActionPerformed(evt);
            }
        });

        stu_name.setBackground(new java.awt.Color(236, 234, 216));
        stu_name.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        stu_name.setForeground(new java.awt.Color(107, 81, 2));
        stu_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_nameActionPerformed(evt);
            }
        });

        phonenum.setBackground(new java.awt.Color(236, 234, 216));
        phonenum.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        phonenum.setForeground(new java.awt.Color(107, 81, 2));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Subject 1 ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Subject 2");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Subject 4");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Subject 3");

        sub_3.setBackground(new java.awt.Color(236, 234, 216));
        sub_3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_3.setForeground(new java.awt.Color(107, 81, 2));
        sub_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_3ActionPerformed(evt);
            }
        });

        sub_4.setBackground(new java.awt.Color(236, 234, 216));
        sub_4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_4.setForeground(new java.awt.Color(107, 81, 2));
        sub_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_4ActionPerformed(evt);
            }
        });

        sub_1.setBackground(new java.awt.Color(236, 234, 216));
        sub_1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_1.setForeground(new java.awt.Color(107, 81, 2));
        sub_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_1ActionPerformed(evt);
            }
        });

        sub_2.setBackground(new java.awt.Color(236, 234, 216));
        sub_2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_2.setForeground(new java.awt.Color(107, 81, 2));
        sub_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Subject 5 ");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Subject 6");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Subject 7");

        sub_6.setBackground(new java.awt.Color(236, 234, 216));
        sub_6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_6.setForeground(new java.awt.Color(107, 81, 2));
        sub_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_6ActionPerformed(evt);
            }
        });

        sub_5.setBackground(new java.awt.Color(236, 234, 216));
        sub_5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_5.setForeground(new java.awt.Color(107, 81, 2));
        sub_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_5ActionPerformed(evt);
            }
        });

        sub_7.setBackground(new java.awt.Color(236, 234, 216));
        sub_7.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        sub_7.setForeground(new java.awt.Color(107, 81, 2));
        sub_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_7ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(81, 66, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(213, 211, 181));
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(81, 66, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(213, 211, 181));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(81, 66, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(213, 211, 181));
        jButton4.setText("Choose File....");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rus_6.setBackground(new java.awt.Color(236, 234, 216));
        rus_6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_6.setForeground(new java.awt.Color(107, 81, 2));
        rus_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_6ActionPerformed(evt);
            }
        });

        rus_7.setBackground(new java.awt.Color(236, 234, 216));
        rus_7.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_7.setForeground(new java.awt.Color(107, 81, 2));
        rus_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_7ActionPerformed(evt);
            }
        });

        rus_5.setBackground(new java.awt.Color(236, 234, 216));
        rus_5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_5.setForeground(new java.awt.Color(107, 81, 2));
        rus_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_5ActionPerformed(evt);
            }
        });

        rus_1.setBackground(new java.awt.Color(236, 234, 216));
        rus_1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_1.setForeground(new java.awt.Color(107, 81, 2));
        rus_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_1ActionPerformed(evt);
            }
        });

        rus_2.setBackground(new java.awt.Color(236, 234, 216));
        rus_2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_2.setForeground(new java.awt.Color(107, 81, 2));
        rus_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_2ActionPerformed(evt);
            }
        });

        rus_4.setBackground(new java.awt.Color(236, 234, 216));
        rus_4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_4.setForeground(new java.awt.Color(107, 81, 2));
        rus_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_4ActionPerformed(evt);
            }
        });

        rus_3.setBackground(new java.awt.Color(236, 234, 216));
        rus_3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        rus_3.setForeground(new java.awt.Color(107, 81, 2));
        rus_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rus_3ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(236, 234, 216));
        jComboBox1.setForeground(new java.awt.Color(107, 81, 2));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AI", "IT", "IS", "CS" }));
        jComboBox1.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Ports");

        jPanel2.setBackground(new java.awt.Color(84, 69, 0));

        show.setBackground(new java.awt.Color(236, 234, 216));
        show.setColumns(20);
        show.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        show.setForeground(new java.awt.Color(107, 81, 2));
        show.setRows(5);
        show.setSelectionColor(new java.awt.Color(57, 57, 0));
        jScrollPane1.setViewportView(show);
        show.getText();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GPA.setBackground(new java.awt.Color(81, 66, 0));
        GPA.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        GPA.setForeground(new java.awt.Color(213, 211, 181));
        GPA.setText("Calculate GPA");
        GPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sub_4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rus_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sub_1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub_2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sub_3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(rus_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(rus_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(32, 32, 32)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(sub_7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rus_7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(sub_6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rus_6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(sub_5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rus_5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(student_name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stu_name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acd_number, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(GPA)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acd_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rus_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rus_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rus_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sub_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rus_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rus_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sub_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rus_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void sub_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_4ActionPerformed
 sub_4.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_sub_4ActionPerformed

    private void sub_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_1ActionPerformed

    private void sub_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_2ActionPerformed

    private void sub_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_6ActionPerformed

    private void sub_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_5ActionPerformed

    private void sub_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // show.setText("");
          stu_name.setText("");
        acd_number.setText("");
          casee.setText("");
            phonenum.setText("");
              sub_4.setText("");
                 sub_3.setText("");
                   sub_2.setText("");
                     sub_1.setText("");
                      sub_5.setText("");
                      sub_7.setText("");
                    sub_6.setText("");
                  rus_1.setText("");
                 rus_2.setText("");
                rus_3.setText("");
               rus_4.setText("");
             rus_5.setText("");
           rus_6.setText("");
        rus_7.setText("");
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rus_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_6ActionPerformed

    private void rus_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_7ActionPerformed

    private void rus_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_5ActionPerformed

    private void rus_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_1ActionPerformed

    private void rus_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_2ActionPerformed
 private void showActionPerformed(java.awt.event.ActionEvent evt) {                                      
       show.getText();
    }   
    private void rus_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_4ActionPerformed

    private void rus_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rus_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rus_3ActionPerformed

    private void stu_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_nameActionPerformed

      
    }//GEN-LAST:event_stu_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        String name =stu_name.getText();
      double num =Double.parseDouble( acd_number.getText());
      String caseee = casee.getText();
       double phonenumber =Double.parseDouble( phonenum.getText());
   
             String subject1 =sub_4.getText();
            String subject2 =sub_3.getText();
           String subject3 =sub_2.getText();
          String subject4 =sub_1.getText();
         String subject5 =sub_5.getText();
        String subject6 =sub_7.getText();
       String subject7 =sub_6.getText();
       double degree1 =Double.parseDouble(rus_1.getText());
         double degree2 =Double.parseDouble(rus_2.getText());
           double degree3 =Double.parseDouble(rus_3.getText());
             double degree4 =Double.parseDouble(rus_4.getText());
              double degree5 =Double.parseDouble(rus_5.getText());
                double degree6 =Double.parseDouble(rus_6.getText());
                  double degree7 =Double.parseDouble(rus_7.getText());
//                  
  double degree []={degree1 , degree2,degree3,degree4,degree5,degree6,degree7};
  String subject []={subject1,subject2,subject3,subject4,subject5,subject6,subject7};
   
    if ( Double.parseDouble(rus_1.getText()) >100 || Double.parseDouble(rus_1.getText())<0 ||
            Double.parseDouble(rus_2.getText()) >100 || Double.parseDouble(rus_2.getText())<0 ||
            Double.parseDouble(rus_3.getText()) >100 || Double.parseDouble(rus_3.getText())<0 ||
            Double.parseDouble(rus_4.getText()) >100 || Double.parseDouble(rus_4.getText())<0 ||
            Double.parseDouble(rus_5.getText()) >100 || Double.parseDouble(rus_5.getText())<0 ||
            Double.parseDouble(rus_6.getText()) >100 || Double.parseDouble(rus_6.getText())<0 ||
            Double.parseDouble(rus_7.getText()) >100 || Double.parseDouble(rus_7.getText())<0 
               
               )
                       {
       
       JOptionPane.showMessageDialog(this,"the degree must be from 0 to 100");
       
       }
            
                  else 
    {
  show.setText(  (show.getText())+ "                  Student Data\n" +"student name : "+(stu_name.getText())+"\n"
                       +
                "student id : "+(acd_number.getText())+"\n"
                       +
                "student case :"+(casee.getText())+"\n"
                       +
                "student phone num : "+(phonenum.getText())+"\n"+"(Grades)--------------------------------\n");
  
  for ( int i = 0 ; i < 7; i++ )
  {
  show.setText(show.getText()+ subject [i] +" : "+degree [i]+"\n"); 
  }
  show.setText(show.getText()+""+"                                           (" +(counter+1)+")");
    show.setText(show.getText()+"\n"+"======================\n");
       counter++;}
    }//GEN-LAST:event_jButton2ActionPerformed
 private void setIconImage() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
    private void caseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      JFileChooser fileChooser = new JFileChooser();   
      fileChooser.showOpenDialog(fileChooser);
    }//GEN-LAST:event_jButton4ActionPerformed
private double convertDegreeToGradePoint(double degree) {
    if (degree >= 90) {
        return 12;
    } else if (degree >= 80) {
        return 9;
    } else if (degree >= 70) {
        return 6;
    } else if (degree >= 60) {
        return 3;
    } else {
        return 0;
    }
}

    private void GPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAActionPerformed

       double  point =0;
       
       
        if ( Double.parseDouble(rus_1.getText()) >100 || Double.parseDouble(rus_1.getText())<0 ||
            Double.parseDouble(rus_2.getText()) >100 || Double.parseDouble(rus_2.getText())<0 ||
            Double.parseDouble(rus_3.getText()) >100 || Double.parseDouble(rus_3.getText())<0 ||
            Double.parseDouble(rus_4.getText()) >100 || Double.parseDouble(rus_4.getText())<0 ||
            Double.parseDouble(rus_5.getText()) >100 || Double.parseDouble(rus_5.getText())<0 ||
            Double.parseDouble(rus_6.getText()) >100 || Double.parseDouble(rus_6.getText())<0 ||
            Double.parseDouble(rus_7.getText()) >100 || Double.parseDouble(rus_7.getText())<0 
               
               )
                       {
       
       JOptionPane.showMessageDialog(this,"the degree must be from 0 to 100");
       
       }
else {

      double deg_1 = Double.parseDouble(rus_1.getText());
double deg_2 = Double.parseDouble(rus_2.getText());
double deg_3 = Double.parseDouble(rus_3.getText());
double deg_4 = Double.parseDouble(rus_4.getText());

double totalGradePoints = 0;
totalGradePoints += convertDegreeToGradePoint(Double.parseDouble(rus_1.getText()));
totalGradePoints += convertDegreeToGradePoint(Double.parseDouble(rus_2.getText()));
totalGradePoints += convertDegreeToGradePoint(Double.parseDouble(rus_3.getText()));
totalGradePoints += convertDegreeToGradePoint(Double.parseDouble(rus_4.getText()));

double gpa = totalGradePoints / 12; // Assuming 4 subjects


show.setText(show.getText()+ ""+"GPA: " + gpa+"\n");
        }
        
    }//GEN-LAST:event_GPAActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GPA;
    private javax.swing.JTextField acd_number;
    private javax.swing.JTextField casee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField phonenum;
    private javax.swing.JTextField rus_1;
    private javax.swing.JTextField rus_2;
    private javax.swing.JTextField rus_3;
    private javax.swing.JTextField rus_4;
    private javax.swing.JTextField rus_5;
    private javax.swing.JTextField rus_6;
    private javax.swing.JTextField rus_7;
    private javax.swing.JTextArea show;
    private javax.swing.JTextField stu_name;
    private javax.swing.JLabel student_name;
    private javax.swing.JTextField sub_1;
    private javax.swing.JTextField sub_2;
    private javax.swing.JTextField sub_3;
    private javax.swing.JTextField sub_4;
    private javax.swing.JTextField sub_5;
    private javax.swing.JTextField sub_6;
    private javax.swing.JTextField sub_7;
    // End of variables declaration//GEN-END:variables
}
